cd /Users/jethroestrada/Desktop/External_Projects/AI/examples_05_2025/rag-all-techniques && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/examples_05_2025/mpi4py && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/examples_05_2025/rag-cookbooks && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/examples_05_2025/haystack-cookbook && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/rag_05_2025/ragas && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/rag_05_2025/RAG_Techniques && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/rag_05_2025/ragflow && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/examples_05_2025/haystack-cookbook && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/examples_07_2025/ai-agents-for-beginners && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/spaCy && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/spacy-course && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/llama-cpp-python && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/lm-evaluation-harness && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/KeyBERT && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/mlx && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/mlx-lm && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/mlx-embeddings && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/mlx-vlm && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/mcp-python-sdk && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/examples_05_2025/mlx-examples && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/chatbot/autogen && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/chatbot/autogenhub && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/chatbot/ollama && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/code_agents/GenAI_Agents && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/faster-whisper && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/starlette && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/llama_index && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/langchain && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/langchain-community && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/langchain-experimental && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/langchain-postgres && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/langmem && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/langgraph && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/repo-libs/langsmith-sdk && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/chatbot/crewAI && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/chatbot/crewAI-tools && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/chatbot/crewAI-examples && git pull && \
cd /Users/jethroestrada/Desktop/External_Projects/AI/chatbot/open-webui && git pull
